### ISSUE TITLE
MATLAB errors with "Error on flush." if outputs are displayed on to the command window in R2023a (Windows only)

### ISSUE THREAD

**Issue by asfilion** [mathworks/jupyter-matlab-proxy#54]
I have the proxy set up with R2023a and Python 3.10 and everything seems to work as expected. If I open the MATLAB console and I check my MATLAB version with either 'ver' or 'version' the expected output is produced but it also gives an error: "Error on flush." If I use these commands from a notebook no error is produced. The only information I could find on this error is this thread, which suggests it's an issue with stdout: https://www.mathworks.com/matlabcentral/answers/421899-matlab-runtime-error-on-flush

**Comment by rashedmyt** [comment]
Hi @asfilion

Thank you for trying out MATLAB Integration for Jupyter.

I was able to reproduce the error "Error on flush" in matlab-proxy. This issue seems to affect only MATLAB R2023a version on Windows OS.

I am working on a fix and will update this issue once a new release of matlab-proxy with the fix is available. Thank you again for reporting this issue.
