### ISSUE TITLE
Some operations are a little slow.

### ISSUE THREAD

**Issue by cqgx680** [mathworks/jupyter-matlab-proxy#69]
![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64179651/3f4d2079-2ec2-46fa-b992-cbdd714ce2d4)
![image](https://github.com/mathworks/jupyter-matlab-proxy/assets/64179651/205d95bd-0c1b-4986-881c-708374bccfa1)

As title, these operations may be too slow.

**Comment by rashedmyt** [comment]
Hi @cqgx680 

I have tried to reproduce the issue to check if the operations are slow. However, I was unable to reproduce it. I have tried running `sym(99)^99` and `det(sym(hilb(80)))` and each of them took only 3-4 seconds to complete.

Can you provide the below information to help us investigate the issue.

1. What OS and MATLAB version are you using
2. Have you tried running the same code in MATLAB Live Script to verify that the issue is with the MATLAB Kernel and not the MATLAB itself
3. What is the version of `matlab-proxy` and `jupyter-matlab-proxy` being used. This information can be obtained using `python -m pip list` command.

**Comment by prabhakk-mw** [comment]
@cqgx680 Could you please provide the information requested for us to continue investigating this ?

**Comment by prabhakk-mw** [comment]
@cqgx680 please comment on this issue with the requested information and we will reopen the issue to continue investigation.
Thank you!
