### ISSUE TITLE
MATLAB not accessible after v0.7.2

### ISSUE THREAD

**Issue by asfilion** [mathworks/jupyter-matlab-proxy#72]
I am on Windows 11 with jupyterlab 4, python 3.10 and MATLAB R2023b Update 4. When I use the proxy with v0.7.2, everything works as I would expect. After that release, there is no longer an "Open MATLAB" button on the jupyter lab home page, only the option to open a Notebook with a MATLAB Kernal. If I try to run a MATLAB command in the kernel, I get an error. If I try to open MATLAB from the Notebook, I get a 404 Not Found error when it tries to access http://localhost:8888/matlab.

**Comment by rashedmyt** [comment]
Hi @asfilion

Thank you for reporting this issue.

We were able to reproduce the issue with `jupyter-matlab-proxy>=0.8.0` and `matlab-proxy<0.8.0`. Can you confirm if upgrading the package `matlab-proxy` using `pip install -U matlab-proxy` fixes the issue.

**Comment by asfilion** [comment]
Hi @rashedmyt I tried updating the matlab-proxy and that removed the errors, however the MATLAB desktop page is just a blank page now. So the MATLAB kernel works with notebooks, and the MATLAB desktop page loads without errors, but the desktop isn't there, it's a blank page. I've let it sit for ~10 minutes so I don't think it's just a slow rendering issue.

**Comment by rashedmyt** [comment]
Thank you for confirming that upgrading `matlab-proxy` package fixes the issue of MATLAB not being available.

With regards to the issue of "blank page", we weren't able to reproduce such behavior. Can you try reproducing the issue in a fresh environment. If it is reproducible, check the Network requests sent from the browser while the page is loading for any errors that may be occurring. Also, check if there are any logs printed in the dev console. Please provide images and logs to help us investigate more.

**Comment by rashedmyt** [comment]
Thank you for the screenshots.
 
After investigation, although I wasn't able to reproduce the behavior, it seems like in your case the static files being requested by the html page are having a different MIME type than what they actually are. For example, JS files should have `text/javascript` instead of `application/octet-stream` as shown in the console logs. I found this issue (https://github.com/aio-libs/aiohttp/issues/4777) which might be related to your situation.
 
To confirm this, can you post a screenshot similar to what I have below
 
![MicrosoftTeams-image (1)](https://github.com/mathworks/jupyter-matlab-proxy/assets/25506588/347305d3-662c-4b76-b7ef-9661b43afd0e)

To capture the above network logs, first open the developer tools network tab and then load the page. Please capture the above screenshot for the files `index-css.css`, `dojoConfig-release-global.js` and `bundle.index-jsd-cr.js`.

Apart from this, Have you tried using a different browser or disabling cache? If not please give this a try and let us know the results. Also, are you using any specific environment such as having the jupyter server on a remote machine and accessing it in the local machine browser, running a proxy similar nginx or using VS Code port forwarding ability to access the jupyter.
