### ISSUE TITLE
Error connecting to MATLAB. Check the status of MATLAB by clicking the "Open MATLAB" button. Retry after ensuring MATLAB is running successfully

### ISSUE THREAD

**Issue by rsp34** [mathworks/jupyter-matlab-proxy#91]
Hi,

I'm trying to use the MATLAB Jupyter Kernel.
 
When I try to execute a cell. I receive the following message:

> Error connecting to MATLAB. Check the status of MATLAB by clicking the "Open MATLAB" button. Retry after ensuring MATLAB is running successfully

When I click "Open MATLAB", I enter the token displayed in the command line (shown below) and the web interface opens without issue. I still can't execute cells in the notebook, however.

> Access MATLAB at: http://127.0.0.1:50077/matlab?mwi-auth-token=Oax0jXOEy93hj2Tfq72HBis0hebMXz3w1Nufwhmxlvw

Any help would be greatly appreciated.

Thanks,
Ryan

**Comment by rashedmyt** [comment]
Hi @rsp34 

Thank you for reporting this issue.

From the description of the issue, it seems that the problem is occurring due to jupyter not being able to use matlab-proxy token information.

To help us debug further, can you provide the output of the [troubleshooting](https://raw.githubusercontent.com/mathworks/jupyter-matlab-proxy/main/troubleshooting/troubleshooting.py) script.

Thank you.

**Comment by rashedmyt** [comment]
Hi @rsp34 

Closing this issue as we haven't heard from you.

Please upgrade to the latest version of `jupyter-matlab-proxy` and check if the problem is reproducible. If it is, feel free to reopen this issue and please provide the output of the above mentioned troubleshooting script along with the logs visible in the terminal from which jupyter was started.

Thank you
