### ISSUE TITLE
error using vpa with Jupyter

### ISSUE THREAD

**Issue by zbalkhy** [mathworks/jupyter-matlab-proxy#99]
### Summary

Hello, i'm running into an error trying to use the vpa() command in MATLAB

I've set up a jupyter instance on a remote server using: 'jupyter notebook --no-browser --port=8080'

I've created an ssh tunnel to the server using: 'ssh -L 8080:localhost:8080 <REMOTE_USER>@<REMOTE_HOST>'

in a Jupyter notebook at localhost:8080 i am able to run most matlab commands. However, when trying to run the vpa command i'm met with an error. I've pasted an example code snippet and the corresponding error below. 

I've tried to set the DISPLAY env variable to `export DISPLAY=:0.0` but to no avail. 

I'm sure this is user error on some level since i don't see it in the list of limitations in the documentation. Please advise!  
Thanks!!

`display(digits);
oldDigits = digits(10);
display(digits);
number = vpa(5.12345658);
display(number);` 

MATLAB Kernel Error:
Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('matlab.internal.cef.webwindow')" style="font-weight:bold">matlab.internal.cef.webwindow</a>
DISPLAY environment variable must be set to a valid X11 display.

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('jupyter.execute>processSymbolic', '/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m', 218)" style="font-weight:bold">jupyter.execute>processSymbolic</a> (<a href="matlab: opentoline('/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m',218,0)">line 218</a>)
    webwindow = matlab.internal.cef.webwindow(connector.getUrl(url));

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('jupyter.execute>processOutputs', '/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m', 124)" style="font-weight:bold">jupyter.execute>processOutputs</a> (<a href="matlab: opentoline('/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m',124,0)">line 124</a>)
            result{ii} = processSymbolic(outputData);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('jupyter.execute', '/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m', 54)" style="font-weight:bold">jupyter.execute</a> (<a href="matlab: opentoline('/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/+jupyter/execute.m',54,0)">line 54</a>)
result = processOutputs(resp.outputs);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('processJupyterKernelRequest', '/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/processJupyterKernelRequest.m', 54)" style="font-weight:bold">processJupyterKernelRequest</a> (<a href="matlab: opentoline('/home/zbalkhy/biotoa_env/lib/python3.10/site-packages/jupyter_matlab_kernel/matlab/processJupyterKernelRequest.m',54,0)">line 54</a>)
            output = jupyter.execute(code, kernelId);

Error in connector.internal.fevalMatlab

Error in connector.internal.fevalJSON

**Comment by prabhakk-mw** [comment]
Hi @zbalkhy 
Could you please share the output of executing the troubleshooting.py script as well?

Thanks

**Comment by rashedmyt** [comment]
Hi @zbalkhy 

Thank you for using MATLAB Integration for Jupyter.

The issue you are facing when running MATLAB code containing symbolic equations might be due to misconfigured setup. As mentioned in the [requirements](https://github.com/mathworks/jupyter-matlab-proxy?tab=readme-ov-file#requirements) of this package, on Linux systems, we require `xvfb` to be installed.

Please install `xvfb` using the instructions mentioned in the requirements section and check if the error is reproducible. If it is, please follow the instructions in the [troubleshooting guide](https://github.com/mathworks/jupyter-matlab-proxy?tab=readme-ov-file#requirements) and share the output.

Hope this is helpful

**Comment by prabhakk-mw** [comment]
Hi @zbalkhy 

Its been a few weeks since we have heard from you.
I'm marking this issue as resolved, if the information that @rashedmyt provided above does not help resolve the issue, kindly leave a comment here with the requested information and we will be happy to reopen the investigation.

Thank you for using the MATLAB Integration for Jupyter!
